begin;
select plan(20);
select ok(not has_function_privilege('authenticated','public.assert_accounting_d2_ready()','EXECUTE'),'members cannot authorize D2 cleanup');
select throws_ok('select public.assert_accounting_d2_ready()','P0001','HOLD D2: no active approved acceptance campaign','no campaign fails closed');
insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values('19000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000000','authenticated','authenticated','d2-gate@example.test','',now(),now(),now(),'{}','{}');
insert into app_users(id,email,full_name) values('19000000-0000-0000-0000-000000000001','d2-gate@example.test','Gate Reviewer');
insert into orgs(id,name,slug,created_by) values('29000000-0000-0000-0000-000000000001','Gate Test','d2-gate-test','19000000-0000-0000-0000-000000000001');
insert into accounting_connections(id,org_id,provider,label,external_account_id,external_account_name,status,connected_by,refresh_failure_count,token_expires_at,refresh_token_expires_at,last_inbound_poll_at) values('39000000-0000-0000-0000-000000000001','29000000-0000-0000-0000-000000000001','qbo','Gate Books','gate-realm','Gate Books','active','19000000-0000-0000-0000-000000000001',0,now()+interval '1 hour',now()+interval '90 days',now());
create table if not exists public.accounting_d2_legacy_archive(org_id uuid,source_table text,entity_id uuid,legacy_data jsonb);
insert into job_runs(job_name,status,started_at,finished_at,duration_ms,http_status) select name,'success',now()-interval '1 minute',now(),60000,200 from unnest(array['accounting-process-outbox','accounting-process-inbound','accounting-process-changes','accounting-reconciliation']) name;
insert into accounting_d2_campaigns(id,candidate_sha,schema_fingerprint,checker_version,parity_version,expected_org_id,expected_connection_id,expected_realm_id,expected_company_name,release_evidence,approved_by,approved_at,started_at,created_at)
values('59000000-0000-0000-0000-000000000001',repeat('a',40),accounting_d2_schema_fingerprint(),'accounting-d2-v1','legacy-present-neutral-equivalence-v1','29000000-0000-0000-0000-000000000001','39000000-0000-0000-0000-000000000001','gate-realm','Gate Books',jsonb_build_object('candidate_sha',repeat('a',40),'runtime_consumers',0,'drop_rehearsal_passed',true,'repairs_verified',true,'artifact_inventory_complete',true,'archive_verified',true),'19000000-0000-0000-0000-000000000001',now()-interval '16 days',now()-interval '15 days',now()-interval '17 days');
select throws_ok('select assert_accounting_d2_ready()','P0001','HOLD D2: explicit final drop approval for this candidate is missing','campaign approval does not imply drop approval');
update accounting_d2_campaigns set release_evidence=release_evidence||jsonb_build_object('drop_approval',jsonb_build_object('candidate_sha',candidate_sha,'reviewed_by','19000000-0000-0000-0000-000000000001','approved_at',now()));
select throws_like('select assert_accounting_d2_ready()','%has missing, failed, or incompatible evidence%','elapsed time without observations does not qualify');
-- Only the PostgreSQL test owner can seed clocked samples; runtime service roles cannot.
insert into accounting_d2_acceptance_samples(campaign_id,checked_at,candidate_sha,schema_fingerprint,checker_version,passed,evidence)
select c.id,(d::date::timestamp at time zone 'UTC')+interval '5 hours',c.candidate_sha,c.schema_fingerprint,c.checker_version,true,'{"complete":true,"scope":"global","blockers":[]}' from accounting_d2_campaigns c cross join generate_series(((now() at time zone 'UTC')::date-7),((now() at time zone 'UTC')::date-1),'1 day') d;
insert into accounting_d2_acceptance_samples(campaign_id,checked_at,candidate_sha,schema_fingerprint,checker_version,passed,evidence) select id,now(),candidate_sha,schema_fingerprint,checker_version,true,'{"complete":true,"scope":"global","blockers":[]}' from accounting_d2_campaigns;
select lives_ok('select assert_accounting_d2_ready()','7 complete days and current measured evidence pass');
create temp table removed_sample as select * from accounting_d2_acceptance_samples order by checked_at limit 1;
delete from accounting_d2_acceptance_samples where id=(select id from removed_sample);
select throws_like('select assert_accounting_d2_ready()','%has missing, failed, or incompatible evidence%','one missing completed date blocks');
insert into accounting_d2_acceptance_samples overriding system value select * from removed_sample;
insert into accounting_d2_acceptance_samples(campaign_id,checked_at,candidate_sha,schema_fingerprint,checker_version,passed,evidence) select campaign_id,checked_at,candidate_sha,schema_fingerprint,checker_version,false,evidence from removed_sample;
select throws_like('select assert_accounting_d2_ready()','%has missing, failed, or incompatible evidence%','a same-day success cannot erase a failed observation');
delete from accounting_d2_acceptance_samples where not passed;
select lives_ok('select assert_accounting_d2_ready()','owner fixture restoration leaves original full evidence valid');
insert into accounting_d2_acceptance_samples(campaign_id,checked_at,candidate_sha,schema_fingerprint,checker_version,passed,evidence) select id,now(),candidate_sha,schema_fingerprint,checker_version,false,'{"complete":true,"scope":"global","blockers":["failure"]}' from accounting_d2_campaigns;
select throws_ok('select assert_accounting_d2_ready()','P0001','HOLD D2: today has failed or incompatible acceptance evidence','today failure blocks earlier clean streak');
delete from accounting_d2_acceptance_samples where not passed;
update accounting_d2_acceptance_samples set checked_at=now()-interval '31 minutes' where checked_at>(now() at time zone 'UTC')::date::timestamp at time zone 'UTC';
select throws_ok('select assert_accounting_d2_ready()','P0001','HOLD D2: refresh measured acceptance evidence on the deployed candidate','stale evidence cannot authorize a current drop');
insert into accounting_d2_acceptance_samples(campaign_id,checked_at,candidate_sha,schema_fingerprint,checker_version,passed,evidence) select id,now(),candidate_sha,schema_fingerprint,checker_version,true,'{"complete":true,"scope":"global","blockers":[]}' from accounting_d2_campaigns;
update accounting_connections set external_account_id='changed' where id='39000000-0000-0000-0000-000000000001';
select throws_ok('select assert_accounting_d2_ready()','P0001','HOLD D2: expected QBO identity or health changed','connection identity is rechecked at drop time');
update accounting_connections set external_account_id='gate-realm' where id='39000000-0000-0000-0000-000000000001';
insert into companies(id,org_id,name,qbo_vendor_name) values('49000000-0000-0000-0000-000000000001','29000000-0000-0000-0000-000000000001','Archive Fixture','legacy name only');
select throws_like('select assert_accounting_d2_ready()','%legacy payloads are not archived exactly%','names-only legacy payload must be archived');
insert into accounting_d2_legacy_archive values('29000000-0000-0000-0000-000000000001','companies','49000000-0000-0000-0000-000000000001','{"qbo_vendor_name":"legacy name only"}');
select lives_ok('select assert_accounting_d2_ready()','exact archive preserves names-only compatibility payload');
update companies set qbo_vendor_name='changed legacy name' where id='49000000-0000-0000-0000-000000000001';
select throws_like('select assert_accounting_d2_ready()','%legacy payloads are not archived exactly%','archive evidence invalidates when source cache changes');
select is(accounting_d2_fill_missing_coding('{"expense_account":null}','{"qbo_expense_account_id":"legacy"}',false)#>>'{expense_account,id}','legacy','JSON null is filled as absent coding');
select is(accounting_d2_fill_missing_coding('{"expense_account":{"id":"neutral"}}','{"qbo_expense_account_id":"legacy"}',false)#>>'{expense_account,id}','neutral','conflicting non-null neutral account is never overwritten');
select is(accounting_d2_fill_missing_coding('{}','{"qbo_vendor_id":"vendor"}',true)->'counterparty',null::jsonb,'company counterparty identity is left in its scoped link');
select is(accounting_d2_fill_missing_coding('{"dimensions":null}','{"qbo_class_id":"class"}',false)#>>'{dimensions,class,id}','class','JSON-null dimensions adopt missing equivalent class');
select throws_ok($$select accounting_d2_fill_missing_coding('{"vendor":{"id":"a"},"counterparty":{"id":"b"}}','{}',false)$$,'P0001','D2 counterparty alias conflicts with canonical coding','alias conflict cannot be silently discarded');
select is(accounting_d2_fill_missing_coding('{"counterparty":{"id":"v"},"dimensions":{"department":{"id":"d"}}}','{"qbo_vendor_id":"old","qbo_class_id":"c"}',false)#>>'{dimensions,department,id}','d','normalization preserves unrelated neutral dimensions');
select * from finish();
rollback;
