"use client"

import { useRef, useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { unwrapAction } from "@/lib/action-result"
import { uploadDocumentFileDirect } from "@/lib/services/files-client"
import type { MeetingTranscript } from "@/lib/services/meeting-transcripts"
import type { MeetingItem } from "@/lib/services/meetings"
import { draftMeetingMinutesAction, pasteMeetingTranscriptAction, queueMeetingAudioTranscriptAction, reviewMeetingProposalAction } from "./actions"

export function MeetingTranscriptPanel({ projectId, meetingId, transcripts, items }: { projectId: string; meetingId: string; transcripts: MeetingTranscript[]; items: MeetingItem[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [paste, setPaste] = useState(""); const [recording, setRecording] = useState(false)
  const recorderRef = useRef<MediaRecorder | null>(null); const streamRef = useRef<MediaStream | null>(null); const chunksRef = useRef<Blob[]>([]); const fileRef = useRef<HTMLInputElement>(null)
  const run = (work: () => Promise<void>) => startTransition(() => void work().catch((error) => toast.error(error instanceof Error ? error.message : "Meeting transcript action failed")))
  async function uploadAudio(file: File, source: "recorded" | "audio_upload") {
    const uploaded = await uploadDocumentFileDirect(file, { projectId, category: "other", folderPath: "/Meetings/Audio", visibility: "private" })
    unwrapAction(await queueMeetingAudioTranscriptAction(projectId, meetingId, uploaded.id, source)); toast.success("Audio queued for transcription"); router.refresh()
  }
  async function beginRecording() {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream); streamRef.current = stream; recorderRef.current = recorder; chunksRef.current = []
    recorder.ondataavailable = (event) => { if (event.data.size) chunksRef.current.push(event.data) }
    recorder.onstop = () => run(async () => { const blob = new Blob(chunksRef.current, { type: recorder.mimeType || "audio/webm" }); await uploadAudio(new File([blob], `meeting-${meetingId}-${Date.now()}.webm`, { type: blob.type }), "recorded") })
    recorder.start(10_000); setRecording(true)
  }
  function stopRecording() { recorderRef.current?.stop(); streamRef.current?.getTracks().forEach((track) => track.stop()); setRecording(false) }
  return <section className="border-t p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-sm font-semibold">Transcript &amp; AI draft</h3><p className="text-xs text-muted-foreground">Recording is visible to participants. Audio is deleted 30 days after a successful transcript; text remains.</p></div>{recording ? <div className="flex items-center gap-2"><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-destructive" /><span className="text-xs font-medium text-destructive">Recording</span><Button size="sm" variant="destructive" onClick={stopRecording}>Stop</Button></div> : <Button size="sm" variant="outline" disabled={pending} onClick={() => void beginRecording().catch((error) => toast.error(error instanceof Error ? error.message : "Microphone unavailable"))}>Record meeting</Button>}</div><div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="space-y-2 border p-3"><p className="text-xs font-medium">Paste Teams / Zoom transcript or VTT</p><Textarea value={paste} onChange={(event) => setPaste(event.target.value)} className="min-h-28" placeholder="Paste transcript text…" /><Button size="sm" disabled={pending || paste.trim().length < 10} onClick={() => run(async () => { unwrapAction(await pasteMeetingTranscriptAction(projectId, meetingId, paste)); setPaste(""); toast.success("Transcript saved"); router.refresh() })}>Save pasted transcript</Button></div><div className="space-y-2 border p-3"><p className="text-xs font-medium">Upload meeting audio</p><Input ref={fileRef} type="file" accept="audio/*,video/webm" /><Button size="sm" variant="outline" disabled={pending} onClick={() => { const file = fileRef.current?.files?.[0]; if (file) run(() => uploadAudio(file, "audio_upload")) }}>Upload &amp; transcribe</Button></div></div><div className="mt-4 space-y-3">{transcripts.length ? transcripts.map((transcript) => <TranscriptRow key={transcript.id} projectId={projectId} transcript={transcript} items={items} pending={pending} run={run} />) : <p className="border border-dashed p-4 text-sm text-muted-foreground">No transcript yet. Record the session, upload audio, or paste a remote-meeting transcript.</p>}</div></section>
}

function TranscriptRow({ projectId, transcript, items, pending, run }: { projectId: string; transcript: MeetingTranscript; items: MeetingItem[]; pending: boolean; run: (work: () => Promise<void>) => void }) {
  const router = useRouter(); const proposals = transcript.draft_proposals
  return <div className="border"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-3"><div><span className="text-sm font-medium capitalize">{transcript.source.replaceAll("_", " ")}</span><span className="ml-2 text-xs text-muted-foreground">{new Date(transcript.created_at).toLocaleString()}</span></div><div className="flex items-center gap-2"><Badge variant={transcript.status === "ready" ? "secondary" : transcript.status === "failed" ? "destructive" : "outline"}>{transcript.status}</Badge>{transcript.status === "ready" ? <Button size="sm" variant="outline" disabled={pending} onClick={() => run(async () => { unwrapAction(await draftMeetingMinutesAction(projectId, transcript.id)); toast.success("Draft proposals ready"); router.refresh() })}>{proposals ? "Redraft proposals" : "Draft minutes"}</Button> : null}</div></div>{transcript.error ? <p className="p-3 text-xs text-destructive">{transcript.error}</p> : null}{transcript.transcript_text ? <details className="border-b p-3"><summary className="cursor-pointer text-xs font-medium">Transcript text</summary><p className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap text-xs text-muted-foreground">{transcript.transcript_text}</p></details> : null}{proposals ? <div className="divide-y">{proposals.existing_items.map((proposal, index) => <Proposal key={`existing-${index}`} projectId={projectId} transcriptId={transcript.id} kind="existing" index={index} proposal={proposal} currentItem={items.find((item) => item.id === proposal.item_id)} pending={pending} run={run} />)}{proposals.new_items.map((proposal, index) => <Proposal key={`new-${index}`} projectId={projectId} transcriptId={transcript.id} kind="new" index={index} proposal={proposal} pending={pending} run={run} />)}</div> : null}</div>
}

function Proposal({ projectId, transcriptId, kind, index, proposal, currentItem, pending, run }: { projectId: string; transcriptId: string; kind: "existing" | "new"; index: number; proposal: any; currentItem?: MeetingItem; pending: boolean; run: (work: () => Promise<void>) => void }) {
  const router = useRouter(); const [discussion, setDiscussion] = useState(proposal.discussion_update ?? proposal.discussion ?? ""); const [topic, setTopic] = useState(proposal.topic ?? "")
  return <div className="grid gap-3 p-3 lg:grid-cols-[140px_1fr_1fr_auto]"><div><Badge variant="outline">{kind === "existing" ? "Update item" : "New item"}</Badge><p className="mt-2 text-xs text-muted-foreground">{proposal.review_status}</p></div>{currentItem ? <div className="border p-2 text-xs"><p className="font-medium">Current · {currentItem.item_number}</p><p className="mt-1">{currentItem.topic}</p><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{currentItem.discussion || "No discussion yet"}</p></div> : <div className="border border-dashed p-2 text-xs text-muted-foreground">New business item</div>}<div className="space-y-2">{kind === "new" ? <Input value={topic} onChange={(event) => setTopic(event.target.value)} /> : <p className="text-xs font-medium">Proposed update</p>}<Textarea value={discussion} onChange={(event) => setDiscussion(event.target.value)} /><p className="text-xs text-muted-foreground">Status: {proposal.proposed_status ?? proposal.status ?? "unchanged"} · BIC: {proposal.proposed_bic ?? proposal.ball_in_court ?? "unchanged"} · Due: {proposal.proposed_due ?? proposal.due_date ?? "unchanged"}</p></div>{proposal.review_status === "pending" ? <div className="flex gap-2 lg:flex-col"><Button size="sm" disabled={pending} onClick={() => run(async () => { unwrapAction(await reviewMeetingProposalAction(projectId, { transcriptId, kind, index, decision: "accepted", edited: kind === "existing" ? { discussion_update: discussion } : { topic, discussion } })); toast.success("Proposal applied"); router.refresh() })}>Accept</Button><Button size="sm" variant="outline" disabled={pending} onClick={() => run(async () => { unwrapAction(await reviewMeetingProposalAction(projectId, { transcriptId, kind, index, decision: "rejected" })); router.refresh() })}>Reject</Button></div> : <Badge variant="secondary" className="h-fit">{proposal.review_status}</Badge>}</div>
}
