import Link from "next/link"

export default function PermissionsAccessIssuesArticle() {
  return (
    <>
      <p>
        If you or your project partners are unable to view specific pages, click action buttons, or log into the Arc workspace, 
        the issue is typically related to role assignments, permission overrides, or expired invitation tokens.
      </p>

      <h2>Issue 1: Hiding Buttons, Tabs, or Menu Actions</h2>
      <p>
        <strong>Symptom:</strong> A team member cannot see a feature (e.g., the <strong>Edit Budget</strong> button is missing, or they cannot see the <strong>Daily Logs</strong> tab).
      </p>
      <h3>Root Cause</h3>
      <p>
        Arc dynamically restricts the user interface based on a combination of the user&apos;s organizational role, project assignments, 
        and fine-grained permission overrides. If a user does not have the required permissions, the UI element is completely hidden to prevent confusion.
      </p>
      <h3>Solutions</h3>
      <ol>
        <li>
          <strong>Check Project Assignments:</strong> Standard users (<code>org_user</code>) can only see projects they are assigned to. 
          An administrator must verify that the user is added to the project by navigating to the <strong>Directory</strong> tab of the project and checking 
          the internal team roster.
        </li>
        <li>
          <strong>Review Permission Overrides:</strong> If the user is assigned to the project but cannot edit specific data, an administrator must navigate to 
          <strong>Settings → Team</strong>, click on the user&apos;s profile, and verify their permission toggles. For example:
          <ul>
            <li>To edit budgets, the user needs <strong>Financial Control</strong> set to write.</li>
            <li>To approve daily superintendent logs, the user needs <strong>Field Operations</strong> set to approve.</li>
            <li>To delete folders or files, the user needs <strong>Documents &amp; Sharing</strong> set to write/delete.</li>
          </ul>
        </li>
      </ol>

      <h2>Issue 2: Expired Team or Portal Invitation Links</h2>
      <p>
        <strong>Symptom:</strong> A new employee or subcontractor clicks an invitation link and receives an <code>Invitation Expired</code> error.
      </p>
      <h3>Root Cause</h3>
      <p>
        For security, all invitation links generated by Arc (whether for internal teammates, subcontractor portals, or client portals) 
        are single-use tokens that expire after exactly <strong>7 days</strong>.
      </p>
      <h3>Solutions</h3>
      <ul>
        <li>
          <strong>For Internal Teammates:</strong> A Workspace Administrator must go to <strong>Settings → Team</strong>, locate the user under the 
          <em>Pending Invites</em> list, click the options menu (three dots) next to their name, and select <strong>Resend Invite</strong>.
        </li>
        <li>
          <strong>For Subcontractors:</strong> Go to the project&apos;s <strong>Directory</strong> tab, locate the vendor contact, click <strong>Manage Portal Token</strong>, 
          and select <strong>Generate New Link</strong>. Send this new link to the subcontractor.
        </li>
        <li>
          <strong>For Clients:</strong> Navigate to the <strong>Client Portal</strong> page within the project settings, locate the client contact, 
          and click <strong>Reset Portal Link</strong> to email a fresh connection token.
        </li>
      </ul>

      <h2>Issue 3: Subcontractors Cannot Sign Subcontracts or Bid Proposals</h2>
      <p>
        <strong>Symptom:</strong> A subcontractor clicks the portal link to sign their contract or submit a bid, but the signature field is disabled 
        or they receive an access error.
      </p>
      <h3>Root Cause</h3>
      <p>
        To sign a document or submit a proposal, the subcontractor contact must match the specific email address registered in the contract details, 
        and their company profile must have active portal tokens. If they forward the link to a coworker, the system blocks the signature to prevent fraudulent execution.
      </p>
      <h3>Solutions</h3>
      <ol>
        <li>
          <strong>Verify the Signatory Email:</strong> Ensure the subcontractor contact listed in the subcontract commitment matches the email address they are using to access the portal. If needed, edit the subcontract details to update the signatory email.
        </li>
        <li>
          <strong>Clear Browser Cache:</strong> If the user is logged into another Arc workspace (e.g., if they are also a user in another contractor&apos;s workspace), their browser cookies may conflict. Have them open the portal link in an <strong>Incognito/Private</strong> browser window.
        </li>
      </ol>
    </>
  )
}
