-- PENDING: production application requires the reviewed per-record decision
-- register and explicit approval. Run before starting the acceptance campaign.
-- This finalizer fills only absent neutral meaning and archives every non-null
-- value in the 38-column compatibility payload. It does not resolve disagreements.
begin;
set local lock_timeout='5s';
set local statement_timeout='120s';
do $$
begin
  if not exists(select 1 from public.accounting_connections where id='e6e4122f-bd9e-480c-b03d-6d4a8cba2eb6' and org_id='eda817f7-b343-46e4-ad17-f61d9fe2e30d' and provider='qbo' and external_account_id='9341456671106880' and status='active') then raise exception 'D2 blocked: expected Patagonia connection identity changed'; end if;
  if (select count(*) from information_schema.columns where table_schema='public' and table_name in ('invoices','project_expenses','vendor_bills','projects','companies') and column_name like 'qbo_%')<>38 then raise exception 'D2 blocked: legacy column inventory changed'; end if;
end $$;
create table if not exists public.accounting_d2_legacy_archive (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete restrict,
  source_table text not null check(source_table in ('invoices','project_expenses','vendor_bills','projects','companies')),
  entity_id uuid not null,
  legacy_data jsonb not null,
  captured_at timestamptz not null default now(),
  unique(org_id,source_table,entity_id)
);
alter table public.accounting_d2_legacy_archive enable row level security;
revoke all on public.accounting_d2_legacy_archive from public,anon,authenticated;
grant select,insert,update on public.accounting_d2_legacy_archive to service_role;
do $$
declare t text;
begin
  foreach t in array array['invoices','project_expenses','vendor_bills','projects','companies'] loop
    execute format($q$insert into public.accounting_d2_legacy_archive(org_id,source_table,entity_id,legacy_data)
      select r.org_id,%L,r.id,legacy.payload from public.%I r cross join lateral(select coalesce(jsonb_object_agg(key,value),'{}'::jsonb) payload from jsonb_each(to_jsonb(r)) where key like 'qbo_%%' and value<>'null'::jsonb) legacy where legacy.payload<>'{}'::jsonb
      on conflict(org_id,source_table,entity_id) do update set legacy_data=excluded.legacy_data,captured_at=now()$q$,t,t);
  end loop;
end $$;
-- Exact approved before-state exclusions preserve intentionally different caches.
-- All other rows keep every non-null canonical reference; disagreements remain
-- visible to the global parity gate below, which rolls this transaction back.
update public.project_expenses e set accounting_coding=public.accounting_d2_fill_missing_coding(e.accounting_coding,to_jsonb(e),e.vendor_company_id is not null)
where e.accounting_coding is distinct from public.accounting_d2_fill_missing_coding(e.accounting_coding,to_jsonb(e),e.vendor_company_id is not null)
  and not exists(select 1 from public.accounting_d2_decisions d where d.org_id=e.org_id and d.entity_type='project_expense' and d.entity_id=e.id::text and d.status in ('approved','applied') and d.disposition in ('preserve_history','test_exclusion','equivalent_reference') and d.before_state<@to_jsonb(e));
update public.vendor_bills b set accounting_coding=public.accounting_d2_fill_missing_coding(b.accounting_coding,to_jsonb(b),b.company_id is not null)
where b.accounting_coding is distinct from public.accounting_d2_fill_missing_coding(b.accounting_coding,to_jsonb(b),b.company_id is not null)
  and not exists(select 1 from public.accounting_d2_decisions d where d.org_id=b.org_id and d.entity_type=case when b.metadata->>'source'='vendor_credit' then 'vendor_credit' else 'bill' end and d.entity_id=b.id::text and d.status in ('approved','applied') and d.disposition in ('preserve_history','test_exclusion','equivalent_reference') and d.before_state<@to_jsonb(b));
do $$
declare p jsonb;
begin
  p:=public.accounting_d2_parity_snapshot();
  if p->>'complete' is distinct from 'true' or p->>'scope' is distinct from 'global' or (p->>'divergent_records')::bigint<>0 then raise exception 'D2 blocked: global identity, counterparty, account, or dimension parity requires review'; end if;
end $$;
commit;
