-- PENDING / NON-DESTRUCTIVE. Do not promote until the application source gate
-- is zero and every conflict raised below has an explicit accounting review.
-- The Supabase CLI is unavailable in this workspace, so this intentionally has
-- no migration timestamp; create the promoted migration with `supabase migration
-- new` only after the D2 approval gate passes.

begin;
set local lock_timeout = '5s';
set local statement_timeout = '120s';

-- Preserve the complete compatibility payload independently of the columns.
-- This makes the eventual drop lossless and gives any later forensic review the
-- exact values that existed at cutover. The table is service-only and RLS-closed.
create table if not exists public.accounting_d2_legacy_archive (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete restrict,
  source_table text not null check (source_table in ('invoices', 'project_expenses', 'vendor_bills', 'projects', 'companies')),
  entity_id uuid not null,
  legacy_data jsonb not null,
  captured_at timestamptz not null default now(),
  unique (org_id, source_table, entity_id)
);
alter table public.accounting_d2_legacy_archive enable row level security;
revoke all on public.accounting_d2_legacy_archive from public, anon, authenticated;
grant select, insert, update on public.accounting_d2_legacy_archive to service_role;

insert into public.accounting_d2_legacy_archive (org_id, source_table, entity_id, legacy_data)
select i.org_id, 'invoices', i.id, jsonb_strip_nulls(jsonb_build_object(
  'qbo_id', i.qbo_id, 'qbo_synced_at', i.qbo_synced_at, 'qbo_sync_status', i.qbo_sync_status
))
from public.invoices i
where jsonb_strip_nulls(jsonb_build_object(
  'qbo_id', i.qbo_id, 'qbo_synced_at', i.qbo_synced_at, 'qbo_sync_status', i.qbo_sync_status
)) <> '{}'::jsonb
on conflict (org_id, source_table, entity_id) do update
set legacy_data = excluded.legacy_data, captured_at = now();

insert into public.accounting_d2_legacy_archive (org_id, source_table, entity_id, legacy_data)
select e.org_id, 'project_expenses', e.id, jsonb_strip_nulls(jsonb_build_object(
  'qbo_id', e.qbo_id, 'qbo_synced_at', e.qbo_synced_at, 'qbo_sync_status', e.qbo_sync_status,
  'qbo_sync_error', e.qbo_sync_error, 'qbo_transaction_type', e.qbo_transaction_type,
  'qbo_expense_account_id', e.qbo_expense_account_id, 'qbo_expense_account_name', e.qbo_expense_account_name,
  'qbo_payment_account_id', e.qbo_payment_account_id, 'qbo_payment_account_name', e.qbo_payment_account_name,
  'qbo_ap_account_id', e.qbo_ap_account_id, 'qbo_ap_account_name', e.qbo_ap_account_name,
  'qbo_vendor_id', e.qbo_vendor_id, 'qbo_vendor_name', e.qbo_vendor_name,
  'qbo_class_id', e.qbo_class_id, 'qbo_class_name', e.qbo_class_name
))
from public.project_expenses e
where jsonb_strip_nulls(jsonb_build_object(
  'qbo_id', e.qbo_id, 'qbo_synced_at', e.qbo_synced_at, 'qbo_sync_status', e.qbo_sync_status,
  'qbo_sync_error', e.qbo_sync_error, 'qbo_transaction_type', e.qbo_transaction_type,
  'qbo_expense_account_id', e.qbo_expense_account_id, 'qbo_expense_account_name', e.qbo_expense_account_name,
  'qbo_payment_account_id', e.qbo_payment_account_id, 'qbo_payment_account_name', e.qbo_payment_account_name,
  'qbo_ap_account_id', e.qbo_ap_account_id, 'qbo_ap_account_name', e.qbo_ap_account_name,
  'qbo_vendor_id', e.qbo_vendor_id, 'qbo_vendor_name', e.qbo_vendor_name,
  'qbo_class_id', e.qbo_class_id, 'qbo_class_name', e.qbo_class_name
)) <> '{}'::jsonb
on conflict (org_id, source_table, entity_id) do update
set legacy_data = excluded.legacy_data, captured_at = now();

insert into public.accounting_d2_legacy_archive (org_id, source_table, entity_id, legacy_data)
select b.org_id, 'vendor_bills', b.id, jsonb_strip_nulls(jsonb_build_object(
  'qbo_id', b.qbo_id, 'qbo_synced_at', b.qbo_synced_at, 'qbo_sync_status', b.qbo_sync_status,
  'qbo_sync_error', b.qbo_sync_error, 'qbo_expense_account_id', b.qbo_expense_account_id,
  'qbo_expense_account_name', b.qbo_expense_account_name, 'qbo_ap_account_id', b.qbo_ap_account_id,
  'qbo_ap_account_name', b.qbo_ap_account_name, 'qbo_vendor_id', b.qbo_vendor_id,
  'qbo_vendor_name', b.qbo_vendor_name, 'qbo_class_id', b.qbo_class_id, 'qbo_class_name', b.qbo_class_name
))
from public.vendor_bills b
where jsonb_strip_nulls(jsonb_build_object(
  'qbo_id', b.qbo_id, 'qbo_synced_at', b.qbo_synced_at, 'qbo_sync_status', b.qbo_sync_status,
  'qbo_sync_error', b.qbo_sync_error, 'qbo_expense_account_id', b.qbo_expense_account_id,
  'qbo_expense_account_name', b.qbo_expense_account_name, 'qbo_ap_account_id', b.qbo_ap_account_id,
  'qbo_ap_account_name', b.qbo_ap_account_name, 'qbo_vendor_id', b.qbo_vendor_id,
  'qbo_vendor_name', b.qbo_vendor_name, 'qbo_class_id', b.qbo_class_id, 'qbo_class_name', b.qbo_class_name
)) <> '{}'::jsonb
on conflict (org_id, source_table, entity_id) do update
set legacy_data = excluded.legacy_data, captured_at = now();

insert into public.accounting_d2_legacy_archive (org_id, source_table, entity_id, legacy_data)
select p.org_id, 'projects', p.id, jsonb_strip_nulls(jsonb_build_object(
  'qbo_class_id', p.qbo_class_id, 'qbo_class_name', p.qbo_class_name,
  'qbo_customer_id', p.qbo_customer_id, 'qbo_customer_name', p.qbo_customer_name
))
from public.projects p
where p.qbo_class_id is not null or p.qbo_customer_id is not null
on conflict (org_id, source_table, entity_id) do update
set legacy_data = excluded.legacy_data, captured_at = now();

insert into public.accounting_d2_legacy_archive (org_id, source_table, entity_id, legacy_data)
select c.org_id, 'companies', c.id, jsonb_strip_nulls(jsonb_build_object(
  'qbo_vendor_id', c.qbo_vendor_id, 'qbo_vendor_name', c.qbo_vendor_name,
  'qbo_vendor_synced_at', c.qbo_vendor_synced_at, 'qbo_vendor_sync_status', c.qbo_vendor_sync_status
))
from public.companies c
where c.qbo_vendor_id is not null or c.qbo_vendor_sync_status is not null
on conflict (org_id, source_table, entity_id) do update
set legacy_data = excluded.legacy_data, captured_at = now();

-- Fill only absent neutral keys. `coalesce` deliberately preserves every
-- existing neutral value; non-null disagreements are reviewed, never overwritten.
update public.project_expenses e
set accounting_coding =
  (coalesce(e.accounting_coding, '{}'::jsonb) - 'vendor' - 'class')
  || jsonb_strip_nulls(jsonb_build_object(
    'transaction_type', coalesce(e.accounting_coding->'transaction_type', to_jsonb(e.qbo_transaction_type)),
    'expense_account', coalesce(e.accounting_coding->'expense_account', case when e.qbo_expense_account_id is not null then jsonb_build_object('id', e.qbo_expense_account_id, 'name', e.qbo_expense_account_name) end),
    'payment_account', coalesce(e.accounting_coding->'payment_account', case when e.qbo_payment_account_id is not null then jsonb_build_object('id', e.qbo_payment_account_id, 'name', e.qbo_payment_account_name) end),
    'ap_account', coalesce(e.accounting_coding->'ap_account', case when e.qbo_ap_account_id is not null then jsonb_build_object('id', e.qbo_ap_account_id, 'name', e.qbo_ap_account_name) end),
    'counterparty', coalesce(e.accounting_coding->'counterparty', e.accounting_coding->'vendor', case when e.vendor_company_id is null and e.qbo_vendor_id is not null then jsonb_build_object('id', e.qbo_vendor_id, 'name', e.qbo_vendor_name) end),
    'dimensions', coalesce(e.accounting_coding->'dimensions', '{}'::jsonb) || case
      when coalesce(e.accounting_coding#>'{dimensions,class}', e.accounting_coding->'class') is not null then jsonb_build_object('class', coalesce(e.accounting_coding#>'{dimensions,class}', e.accounting_coding->'class'))
      when e.qbo_class_id is not null then jsonb_build_object('class', jsonb_build_object('id', e.qbo_class_id, 'name', e.qbo_class_name))
      else '{}'::jsonb end
  ))
where e.accounting_coding ? 'vendor' or e.accounting_coding ? 'class'
   or (e.qbo_transaction_type is not null and e.accounting_coding->'transaction_type' is null)
   or (e.qbo_expense_account_id is not null and e.accounting_coding->'expense_account' is null)
   or (e.qbo_payment_account_id is not null and e.accounting_coding->'payment_account' is null)
   or (e.qbo_ap_account_id is not null and e.accounting_coding->'ap_account' is null)
   or (e.vendor_company_id is null and e.qbo_vendor_id is not null and e.accounting_coding->'counterparty' is null)
   or (e.qbo_class_id is not null and e.accounting_coding#>'{dimensions,class}' is null);

update public.vendor_bills b
set accounting_coding =
  (coalesce(b.accounting_coding, '{}'::jsonb) - 'vendor' - 'class')
  || jsonb_strip_nulls(jsonb_build_object(
    'expense_account', coalesce(b.accounting_coding->'expense_account', case when b.qbo_expense_account_id is not null then jsonb_build_object('id', b.qbo_expense_account_id, 'name', b.qbo_expense_account_name) end),
    'ap_account', coalesce(b.accounting_coding->'ap_account', case when b.qbo_ap_account_id is not null then jsonb_build_object('id', b.qbo_ap_account_id, 'name', b.qbo_ap_account_name) end),
    'counterparty', coalesce(b.accounting_coding->'counterparty', b.accounting_coding->'vendor', case when b.company_id is null and b.qbo_vendor_id is not null then jsonb_build_object('id', b.qbo_vendor_id, 'name', b.qbo_vendor_name) end),
    'dimensions', coalesce(b.accounting_coding->'dimensions', '{}'::jsonb) || case
      when coalesce(b.accounting_coding#>'{dimensions,class}', b.accounting_coding->'class') is not null then jsonb_build_object('class', coalesce(b.accounting_coding#>'{dimensions,class}', b.accounting_coding->'class'))
      when b.qbo_class_id is not null then jsonb_build_object('class', jsonb_build_object('id', b.qbo_class_id, 'name', b.qbo_class_name))
      else '{}'::jsonb end
  ))
where b.accounting_coding ? 'vendor' or b.accounting_coding ? 'class'
   or (b.qbo_expense_account_id is not null and b.accounting_coding->'expense_account' is null)
   or (b.qbo_ap_account_id is not null and b.accounting_coding->'ap_account' is null)
   or (b.company_id is null and b.qbo_vendor_id is not null and b.accounting_coding->'counterparty' is null)
   or (b.qbo_class_id is not null and b.accounting_coding#>'{dimensions,class}' is null);

-- Fail closed for Patagonia's immutable connection identity and for every
-- non-null coding disagreement. A reviewer must choose the authoritative value;
-- this migration never guesses which account should receive customer money.
do $$
declare
  v_target_rows bigint;
  v_conflicts bigint;
begin
  select count(*) into v_target_rows
  from public.orgs o
  join public.accounting_connections c on c.org_id = o.id
  where o.name = 'Patagonia Development LLC' and c.provider = 'qbo' and c.status = 'active'
    and c.external_account_id = '9341456671106880';
  if v_target_rows <> 1 then
    raise exception 'D2 blocked: Patagonia active QBO realm identity changed (expected exactly one row)';
  end if;

  select
    (select count(*) from public.project_expenses e
      where e.qbo_expense_account_id is not null
        and e.accounting_coding#>>'{expense_account,id}' is not null
        and e.accounting_coding#>>'{expense_account,id}' is distinct from e.qbo_expense_account_id)
    +
    (select count(*) from public.vendor_bills b
      where b.qbo_expense_account_id is not null
        and b.accounting_coding#>>'{expense_account,id}' is not null
        and b.accounting_coding#>>'{expense_account,id}' is distinct from b.qbo_expense_account_id)
  into v_conflicts;
  if v_conflicts > 0 then
    raise exception 'D2 blocked: % non-null legacy/neutral expense-account conflicts require disposition', v_conflicts;
  end if;
end
$$;

commit;
