import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer"

export type DrawSummaryPdfData = {
  orgName?: string
  projectName?: string
  invoiceNumber: string
  drawNumber: number
  drawTitle: string
  drawAmountCents: number
  contractTotalCents: number
  approvedChangeOrdersCents: number
  revisedContractCents: number
  paidToDateCents: number
  remainingAfterThisDrawCents: number
  issuedAtIso: string
}

function formatCurrency(cents: number) {
  const dollars = cents / 100
  return dollars.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 })
}

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 11, fontFamily: "Helvetica" },
  header: { marginBottom: 18 },
  title: { fontSize: 18, fontWeight: 700 },
  subtitle: { marginTop: 4, color: "#555" },
  section: { marginTop: 16, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#eee" },
  row: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  label: { color: "#555" },
  value: { fontWeight: 700 },
  small: { fontSize: 9, color: "#777", marginTop: 14 },
})

function DrawSummaryDocument({ data }: { data: DrawSummaryPdfData }) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Draw Request Summary</Text>
          <Text style={styles.subtitle}>
            Draw {data.drawNumber}: {data.drawTitle}
          </Text>
          <Text style={styles.subtitle}>
            Invoice #{data.invoiceNumber} • Issued {data.issuedAtIso}
          </Text>
          {data.projectName ? <Text style={styles.subtitle}>Project: {data.projectName}</Text> : null}
          {data.orgName ? <Text style={styles.subtitle}>Builder: {data.orgName}</Text> : null}
        </View>

        <View style={styles.section}>
          <Text style={{ fontSize: 12, fontWeight: 700 }}>Summary</Text>

          <View style={styles.row}>
            <Text style={styles.label}>Contract total</Text>
            <Text style={styles.value}>{formatCurrency(data.contractTotalCents)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Approved change orders</Text>
            <Text style={styles.value}>{formatCurrency(data.approvedChangeOrdersCents)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Revised contract</Text>
            <Text style={styles.value}>{formatCurrency(data.revisedContractCents)}</Text>
          </View>

          <View style={{ marginTop: 10, borderTopWidth: 1, borderTopColor: "#eee" }} />

          <View style={styles.row}>
            <Text style={styles.label}>Paid-to-date</Text>
            <Text style={styles.value}>{formatCurrency(data.paidToDateCents)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>This draw amount</Text>
            <Text style={styles.value}>{formatCurrency(data.drawAmountCents)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Remaining after this draw</Text>
            <Text style={styles.value}>{formatCurrency(data.remainingAfterThisDrawCents)}</Text>
          </View>
        </View>

        <Text style={styles.small}>
          Generated by Arc. This summary is for convenience and does not replace the executed contract and approved change orders.
        </Text>
      </Page>
    </Document>
  )
}

export async function renderDrawSummaryPdf(data: DrawSummaryPdfData): Promise<Buffer> {
  const pdf = await renderToBuffer(<DrawSummaryDocument data={data} />)
  return Buffer.from(pdf)
}

