import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer"

/**
 * AIA G702/G703-style payment application rendered from the project's draw
 * schedule. Page 1 mirrors the G702 application & certificate summary; page 2
 * mirrors the G703 continuation sheet with the draw schedule as the schedule
 * of values. Styled as an equivalent, not a licensed AIA form.
 */

export type PayApplicationLine = {
  itemNo: string
  description: string
  scheduledValueCents: number
  previousCents: number
  thisPeriodCents: number
}

export type PayApplicationPdfData = {
  applicationNumber: number
  applicationDateIso: string
  periodToIso?: string | null
  projectName: string
  propertyDescription?: string | null
  ownerName: string
  contractorName: string
  contractDateIso?: string | null
  originalContractCents: number
  changeOrdersCents: number
  retainagePercent: number
  lines: PayApplicationLine[]
  invoiceNumber?: string | null
}

function money(cents: number) {
  return (cents / 100).toLocaleString("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 })
}

function fdate(value?: string | null) {
  if (!value) return "—"
  const d = new Date(value)
  return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })
}

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, fontFamily: "Helvetica" },
  title: { fontSize: 14, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 9, color: "#555", marginTop: 2 },
  headerGrid: { flexDirection: "row", marginTop: 14, gap: 24 },
  headerCol: { flex: 1 },
  headerLabel: { color: "#555", marginTop: 6 },
  headerValue: { fontFamily: "Helvetica-Bold", marginTop: 1 },
  section: { marginTop: 18 },
  sectionTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 8 },
  sumRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3.5, borderBottomWidth: 0.5, borderBottomColor: "#ddd" },
  sumLabel: { color: "#333" },
  sumValue: { fontFamily: "Helvetica-Bold" },
  sumTotalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 5, borderBottomWidth: 1.5, borderBottomColor: "#111", marginTop: 2 },
  cert: { marginTop: 22, fontSize: 8.5, color: "#333", lineHeight: 1.5 },
  signatureRow: { flexDirection: "row", gap: 32, marginTop: 28 },
  signatureLine: { flex: 1, borderTopWidth: 1, borderTopColor: "#111", paddingTop: 4 },
  small: { fontSize: 7.5, color: "#777", marginTop: 24 },
  // G703 table
  table: { marginTop: 10 },
  th: { flexDirection: "row", borderBottomWidth: 1.5, borderBottomColor: "#111", paddingBottom: 4, fontFamily: "Helvetica-Bold" },
  tr: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#ddd", paddingVertical: 4 },
  trTotal: { flexDirection: "row", borderTopWidth: 1.5, borderTopColor: "#111", paddingVertical: 5, fontFamily: "Helvetica-Bold" },
  cItem: { width: "6%" },
  cDesc: { width: "26%", paddingRight: 4 },
  cNum: { width: "13.6%", textAlign: "right" },
})

function G702Page({ data, totals }: { data: PayApplicationPdfData; totals: Totals }) {
  return (
    <Page size="LETTER" style={styles.page}>
      <Text style={styles.title}>Application and Certificate for Payment</Text>
      <Text style={styles.subtitle}>Payment application (G702-style summary) • Generated by Arc</Text>

      <View style={styles.headerGrid}>
        <View style={styles.headerCol}>
          <Text style={styles.headerLabel}>To (Owner)</Text>
          <Text style={styles.headerValue}>{data.ownerName}</Text>
          <Text style={styles.headerLabel}>From (Contractor)</Text>
          <Text style={styles.headerValue}>{data.contractorName}</Text>
          <Text style={styles.headerLabel}>Project</Text>
          <Text style={styles.headerValue}>{data.projectName}</Text>
          {data.propertyDescription ? <Text style={{ color: "#555" }}>{data.propertyDescription}</Text> : null}
        </View>
        <View style={styles.headerCol}>
          <Text style={styles.headerLabel}>Application No.</Text>
          <Text style={styles.headerValue}>{data.applicationNumber}</Text>
          <Text style={styles.headerLabel}>Application date</Text>
          <Text style={styles.headerValue}>{fdate(data.applicationDateIso)}</Text>
          <Text style={styles.headerLabel}>Period to</Text>
          <Text style={styles.headerValue}>{fdate(data.periodToIso)}</Text>
          {data.invoiceNumber ? (
            <>
              <Text style={styles.headerLabel}>Invoice</Text>
              <Text style={styles.headerValue}>{data.invoiceNumber}</Text>
            </>
          ) : null}
          {data.contractDateIso ? (
            <>
              <Text style={styles.headerLabel}>Contract date</Text>
              <Text style={styles.headerValue}>{fdate(data.contractDateIso)}</Text>
            </>
          ) : null}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Contractor&apos;s Application for Payment</Text>
        <View style={styles.sumRow}>
          <Text style={styles.sumLabel}>1. Original contract sum</Text>
          <Text style={styles.sumValue}>{money(data.originalContractCents)}</Text>
        </View>
        <View style={styles.sumRow}>
          <Text style={styles.sumLabel}>2. Net change by change orders</Text>
          <Text style={styles.sumValue}>{money(data.changeOrdersCents)}</Text>
        </View>
        <View style={styles.sumRow}>
          <Text style={styles.sumLabel}>3. Contract sum to date (1 + 2)</Text>
          <Text style={styles.sumValue}>{money(totals.contractSumToDateCents)}</Text>
        </View>
        <View style={styles.sumRow}>
          <Text style={styles.sumLabel}>4. Total completed and stored to date</Text>
          <Text style={styles.sumValue}>{money(totals.completedToDateCents)}</Text>
        </View>
        <View style={styles.sumRow}>
          <Text style={styles.sumLabel}>5. Retainage ({data.retainagePercent.toFixed(1)}% of completed work)</Text>
          <Text style={styles.sumValue}>{money(totals.retainageCents)}</Text>
        </View>
        <View style={styles.sumRow}>
          <Text style={styles.sumLabel}>6. Total earned less retainage (4 − 5)</Text>
          <Text style={styles.sumValue}>{money(totals.earnedLessRetainageCents)}</Text>
        </View>
        <View style={styles.sumRow}>
          <Text style={styles.sumLabel}>7. Less previous certificates for payment</Text>
          <Text style={styles.sumValue}>{money(totals.previousCertificatesCents)}</Text>
        </View>
        <View style={styles.sumTotalRow}>
          <Text>8. Current payment due</Text>
          <Text>{money(totals.currentPaymentDueCents)}</Text>
        </View>
        <View style={styles.sumRow}>
          <Text style={styles.sumLabel}>9. Balance to finish, including retainage (3 − 6)</Text>
          <Text style={styles.sumValue}>{money(totals.balanceToFinishCents)}</Text>
        </View>
      </View>

      <Text style={styles.cert}>
        The undersigned Contractor certifies that to the best of the Contractor&apos;s knowledge, information and belief the
        Work covered by this Application for Payment has been completed in accordance with the Contract Documents, that all
        amounts have been paid by the Contractor for Work for which previous Certificates for Payment were issued and
        payments received from the Owner, and that current payment shown herein is now due.
      </Text>

      <View style={styles.signatureRow}>
        <View style={styles.signatureLine}>
          <Text>{data.contractorName}</Text>
          <Text style={{ color: "#555" }}>Contractor — authorized signature / date</Text>
        </View>
        <View style={styles.signatureLine}>
          <Text> </Text>
          <Text style={{ color: "#555" }}>Owner / lender approval — signature / date</Text>
        </View>
      </View>

      <Text style={styles.small}>
        Continuation sheet (schedule of values) attached. This document is an AIA G702/G703-equivalent summary generated
        from the project draw schedule; it is not a licensed AIA form.
      </Text>
    </Page>
  )
}

function G703Page({ data, totals }: { data: PayApplicationPdfData; totals: Totals }) {
  return (
    <Page size="LETTER" orientation="landscape" style={styles.page}>
      <Text style={styles.title}>Continuation Sheet</Text>
      <Text style={styles.subtitle}>
        Schedule of values (G703-style) • Application {data.applicationNumber} • {fdate(data.applicationDateIso)} • {data.projectName}
      </Text>

      <View style={styles.table}>
        <View style={styles.th}>
          <Text style={styles.cItem}>No.</Text>
          <Text style={styles.cDesc}>Description of work</Text>
          <Text style={styles.cNum}>Scheduled value</Text>
          <Text style={styles.cNum}>Previous applications</Text>
          <Text style={styles.cNum}>This period</Text>
          <Text style={styles.cNum}>Completed to date</Text>
          <Text style={styles.cNum}>%</Text>
          <Text style={styles.cNum}>Balance to finish</Text>
        </View>
        {data.lines.map((line) => {
          const completed = line.previousCents + line.thisPeriodCents
          const pct = line.scheduledValueCents > 0 ? (completed / line.scheduledValueCents) * 100 : 0
          return (
            <View key={line.itemNo} style={styles.tr}>
              <Text style={styles.cItem}>{line.itemNo}</Text>
              <Text style={styles.cDesc}>{line.description}</Text>
              <Text style={styles.cNum}>{money(line.scheduledValueCents)}</Text>
              <Text style={styles.cNum}>{money(line.previousCents)}</Text>
              <Text style={styles.cNum}>{money(line.thisPeriodCents)}</Text>
              <Text style={styles.cNum}>{money(completed)}</Text>
              <Text style={styles.cNum}>{pct.toFixed(0)}%</Text>
              <Text style={styles.cNum}>{money(line.scheduledValueCents - completed)}</Text>
            </View>
          )
        })}
        <View style={styles.trTotal}>
          <Text style={styles.cItem}> </Text>
          <Text style={styles.cDesc}>Total</Text>
          <Text style={styles.cNum}>{money(totals.scheduledTotalCents)}</Text>
          <Text style={styles.cNum}>{money(totals.previousTotalCents)}</Text>
          <Text style={styles.cNum}>{money(totals.thisPeriodTotalCents)}</Text>
          <Text style={styles.cNum}>{money(totals.completedToDateCents)}</Text>
          <Text style={styles.cNum}>
            {totals.scheduledTotalCents > 0 ? ((totals.completedToDateCents / totals.scheduledTotalCents) * 100).toFixed(0) : "0"}%
          </Text>
          <Text style={styles.cNum}>{money(totals.scheduledTotalCents - totals.completedToDateCents)}</Text>
        </View>
      </View>

      <Text style={styles.small}>
        Retainage of {data.retainagePercent.toFixed(1)}% is applied on completed work on the application summary page.
      </Text>
    </Page>
  )
}

type Totals = ReturnType<typeof computeTotals>

function computeTotals(data: PayApplicationPdfData) {
  const scheduledTotalCents = data.lines.reduce((sum, l) => sum + l.scheduledValueCents, 0)
  const previousTotalCents = data.lines.reduce((sum, l) => sum + l.previousCents, 0)
  const thisPeriodTotalCents = data.lines.reduce((sum, l) => sum + l.thisPeriodCents, 0)
  const completedToDateCents = previousTotalCents + thisPeriodTotalCents
  const retainageRate = data.retainagePercent / 100
  const retainageCents = Math.round(completedToDateCents * retainageRate)
  const previousRetainageCents = Math.round(previousTotalCents * retainageRate)
  const contractSumToDateCents = data.originalContractCents + data.changeOrdersCents
  const earnedLessRetainageCents = completedToDateCents - retainageCents
  const previousCertificatesCents = previousTotalCents - previousRetainageCents
  return {
    scheduledTotalCents,
    previousTotalCents,
    thisPeriodTotalCents,
    completedToDateCents,
    retainageCents,
    contractSumToDateCents,
    earnedLessRetainageCents,
    previousCertificatesCents,
    currentPaymentDueCents: earnedLessRetainageCents - previousCertificatesCents,
    balanceToFinishCents: contractSumToDateCents - earnedLessRetainageCents,
  }
}

export async function renderPayApplicationPdf(data: PayApplicationPdfData): Promise<Buffer> {
  const totals = computeTotals(data)
  const pdf = await renderToBuffer(
    <Document>
      <G702Page data={data} totals={totals} />
      <G703Page data={data} totals={totals} />
    </Document>,
  )
  return Buffer.from(pdf)
}
