import type { ChartAccountTemplate } from "@/lib/services/books/types"

export const SYSTEM_ACCOUNT_CODES = {
  operatingCash: "1000",
  undepositedFunds: "1010",
  accountsReceivable: "1100",
  retainageReceivable: "1110",
  contractAsset: "1150",
  prepaidExpenses: "1200",
  fixedAssets: "1500",
  accumulatedDepreciation: "1590",
  accountsPayable: "2000",
  retainagePayable: "2010",
  creditCards: "2100",
  payrollClearing: "2200",
  salesUseTaxPayable: "2250",
  customerDeposits: "2300",
  contractLiability: "2350",
  currentDebt: "2400",
  longTermDebt: "2500",
  ownerEquity: "3000",
  ownerContributions: "3010",
  ownerDistributions: "3020",
  retainedEarnings: "3100",
  constructionRevenue: "4000",
  otherRevenue: "4900",
  jobCosts: "5000",
  subcontractorCosts: "5010",
  materialCosts: "5020",
  laborCosts: "5030",
  equipmentCosts: "5040",
  warrantyCosts: "5050",
  rentExpense: "6000",
  insuranceExpense: "6010",
  softwareExpense: "6020",
  professionalFees: "6030",
  utilitiesExpense: "6040",
  bankFees: "6050",
  interestExpense: "6060",
  payrollExpense: "6070",
  depreciationExpense: "6080",
  otherExpense: "6900",
} as const

export const CONSTRUCTION_CHART_TEMPLATE: readonly ChartAccountTemplate[] = [
  { code: "1000", name: "Operating cash", accountType: "asset", subtype: "cash", normalBalance: "debit", cashFlowCategory: "cash", system: true },
  { code: "1010", name: "Undeposited funds", accountType: "asset", subtype: "undeposited_funds", normalBalance: "debit", cashFlowCategory: "operating", system: true },
  { code: "1100", name: "Accounts receivable", accountType: "asset", subtype: "accounts_receivable", normalBalance: "debit", cashFlowCategory: "operating", system: true },
  { code: "1110", name: "Retainage receivable", accountType: "asset", subtype: "retainage_receivable", normalBalance: "debit", cashFlowCategory: "operating", system: true },
  { code: "1150", name: "Contract assets / costs in excess", accountType: "asset", subtype: "costs_in_excess", normalBalance: "debit", cashFlowCategory: "operating", system: true },
  { code: "1200", name: "Prepaid expenses", accountType: "asset", subtype: "prepaid_expenses", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "1500", name: "Property and equipment", accountType: "asset", subtype: "fixed_assets", normalBalance: "debit", cashFlowCategory: "investing", system: false },
  { code: "1590", name: "Accumulated depreciation", accountType: "asset", subtype: "accumulated_depreciation", normalBalance: "credit", cashFlowCategory: "investing", system: false },
  { code: "2000", name: "Accounts payable", accountType: "liability", subtype: "accounts_payable", normalBalance: "credit", cashFlowCategory: "operating", system: true },
  { code: "2010", name: "Retainage payable", accountType: "liability", subtype: "retainage_payable", normalBalance: "credit", cashFlowCategory: "operating", system: true },
  { code: "2100", name: "Credit cards payable", accountType: "liability", subtype: "credit_card", normalBalance: "credit", cashFlowCategory: "operating", system: true },
  { code: "2200", name: "Payroll clearing", accountType: "liability", subtype: "payroll_clearing", normalBalance: "credit", cashFlowCategory: "operating", system: true },
  { code: "2250", name: "Sales and use tax payable", accountType: "liability", subtype: "sales_use_tax", normalBalance: "credit", cashFlowCategory: "operating", system: true },
  { code: "2300", name: "Customer deposits", accountType: "liability", subtype: "customer_deposits", normalBalance: "credit", cashFlowCategory: "operating", system: true },
  { code: "2350", name: "Contract liabilities / billings in excess", accountType: "liability", subtype: "billings_in_excess", normalBalance: "credit", cashFlowCategory: "operating", system: true },
  { code: "2400", name: "Current debt", accountType: "liability", subtype: "current_debt", normalBalance: "credit", cashFlowCategory: "financing", system: false },
  { code: "2500", name: "Long-term debt", accountType: "liability", subtype: "long_term_debt", normalBalance: "credit", cashFlowCategory: "financing", system: false },
  { code: "3000", name: "Owner equity", accountType: "equity", subtype: "owner_equity", normalBalance: "credit", cashFlowCategory: "financing", system: true },
  { code: "3010", name: "Owner contributions", accountType: "equity", subtype: "owner_contributions", normalBalance: "credit", cashFlowCategory: "financing", system: true },
  { code: "3020", name: "Owner distributions", accountType: "equity", subtype: "owner_distributions", normalBalance: "debit", cashFlowCategory: "financing", system: true },
  { code: "3100", name: "Retained earnings", accountType: "equity", subtype: "retained_earnings", normalBalance: "credit", system: true },
  { code: "4000", name: "Construction revenue", accountType: "income", subtype: "construction_revenue", normalBalance: "credit", cashFlowCategory: "operating", system: true },
  { code: "4900", name: "Other revenue", accountType: "income", subtype: "other_revenue", normalBalance: "credit", cashFlowCategory: "operating", system: false },
  { code: "5000", name: "Job costs", accountType: "cogs", subtype: "job_costs", normalBalance: "debit", cashFlowCategory: "operating", system: true },
  { code: "5010", name: "Subcontractor costs", accountType: "cogs", subtype: "subcontractor_costs", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "5020", name: "Material costs", accountType: "cogs", subtype: "material_costs", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "5030", name: "Direct labor", accountType: "cogs", subtype: "direct_labor", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "5040", name: "Equipment costs", accountType: "cogs", subtype: "equipment_costs", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "5050", name: "Warranty costs", accountType: "cogs", subtype: "warranty_costs", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6000", name: "Rent", accountType: "expense", subtype: "rent", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6010", name: "Insurance", accountType: "expense", subtype: "insurance", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6020", name: "Software and subscriptions", accountType: "expense", subtype: "software", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6030", name: "Professional fees", accountType: "expense", subtype: "professional_fees", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6040", name: "Utilities", accountType: "expense", subtype: "utilities", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6050", name: "Bank fees", accountType: "expense", subtype: "bank_fees", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6060", name: "Interest expense", accountType: "expense", subtype: "interest", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6070", name: "Payroll expense", accountType: "expense", subtype: "payroll", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6080", name: "Depreciation expense", accountType: "expense", subtype: "depreciation", normalBalance: "debit", cashFlowCategory: "operating", system: false },
  { code: "6900", name: "Other expense", accountType: "expense", subtype: "other_expense", normalBalance: "debit", cashFlowCategory: "operating", system: false },
] as const

